apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-xbub
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-xbub
    app.kubernetes.io/part-of: application-sample
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-xbub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-xbub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-xbub
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:N6juw-devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-xbub
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
