apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-odql
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-devfile-multi-component-odql
    app.kubernetes.io/part-of: application-sample
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-odql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-odql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-devfile-multi-component-odql
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:N6juw-devfile-sample-python-basic-rhtap-devfile-multi-component-odql
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
